### ISSUE TITLE
Can't download only episode

### ISSUE THREAD

**Issue by glensc** [smarbaa/yt-dlp-ugly-err#2]
I can't download just an episode, it downloads everything.

This download everything should only happen if downloading via show link.

episode 1:
- https://arhiiv.err.ee/video/vaata/patu-1

show link:
- https://arhiiv.err.ee/video/vaata/patu

**Comment by smarbaa** [comment]
Thanks. It's a bug obviously.
It appears that I have made a wrong assumption that a series and an episode can be distinguished by their respective urls alone. But it's not the case.

Urls like

* https://arhiiv.err.ee/video/patu
* https://arhiiv.err.ee/video/vaata/patu
* https://arhiiv.err.ee/video/seeria/patu

and even

* https://arhiiv.err.ee/video/seeria/patu-1

all point to a series.
But not

* https://arhiiv.err.ee/video/seeria/patu-100

because there only are 9 episodes.

Whereas urls like

* https://arhiiv.err.ee/video/vaata/patu-1
* https://arhiiv.err.ee/video/patu-1

point to an episode and only indirectly to the series they belong to.

I shall look into this hairy mess over the weekend probably.

**Comment by glensc** [comment]
there's also one extra url I found:
1. go to episode
2. click info tab
3. click on "kopeeri pysiviide"

you'll get URL like:
- https://arhiiv.err.ee/guid/201005071117426010010002081001517C41A040000005020B00000D0F007729

but not sure how to get such for show

also, if you navigate their site, there's no "show" URL, it always goes to first episode. this looks like show URL:
- https://arhiiv.err.ee/video/vaata/patu

but you won't get it from navigating. i made it up by editing url

**Comment by smarbaa** [comment]
I think i got it covered now, at least, all except the 'pysiviide' type of urls.

I had a hard time with '--yes-playlist' and '--no-playlist' parameters. Yt-dlp assigns always no-playlist false, and yes-playlist true, consequently. And I wanted to be able to download a list even if only an episode type of url is given. I had to abandon this foolish idea and to settle down on a much more reasonable principle of only doing things that are explicitly requested. So, series urls download serieses and episode urls single episodes. Works well enough.

I only implemented the new principle for UglyERRArhiiv,  I shall work on other services some time later in the week perhaps.

Also, I shall leave the issue open until I have figured out what to do with these 'pysiviide' type of urls.

**Comment by smarbaa** [comment]
@glensc
Permanent links like

* https://arhiiv.err.ee/guid/201005071117426010010002081001517C41A040000005020B00000D0F007729

work out of the box, as they are nothing else but server side redirects and yt-dlp's generic extractor handles them excellently. There is nothing I can do to make it better.
